<?php

declare(strict_types=1);

namespace App\Support\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Model;

/**
 * Base class for every domain model.
 *
 * Primary keys are ULIDs: they sort lexicographically by creation time (so
 * B-tree locality is preserved on large tables), they can be generated by the
 * application without a database round-trip — which matters for idempotent
 * imports and channel synchronisation — and they are safe to expose in URLs
 * because they cannot be enumerated.
 */
abstract class BaseModel extends Model
{
    use HasUlids;

    public $incrementing = false;

    protected $keyType = 'string';

    /**
     * Guard nothing by default and instead declare `$fillable` per model.
     * Every model in this codebase sets its own fillable list.
     */
    protected $guarded = [];
}
